# Generated by Django 6.0 on 2026-07-23 02:53

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(error_messages={'unique': 'Já existe um usuário com este nome.'}, help_text='Necessário. 150 caracteres ou menos. Letras, dígitos e @/./+/-/_/espaços.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='O nome de usuário pode conter letras, números, espaços, hífens e underlines.', regex='^[\\w\\s.-]+$')], verbose_name='Nome de Usuário')),
                ('role', models.CharField(choices=[('GESTOR', 'Gestor'), ('OPERADOR', 'Operador'), ('DENTISTA', 'Dentista')], default='DENTISTA', max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número do CRO')),
                ('esta_arquivado', models.BooleanField(default=False, verbose_name='Está na Lixeira')),
                ('cadastro_confirmado', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_entregavel', models.FileField(blank=True, null=True, upload_to='entregas/')),
                ('nome_paciente', models.CharField(max_length=100, verbose_name='Nome do Paciente')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1, verbose_name='Sexo')),
                ('dentes', models.CharField(help_text='Ex: 11, 12, 21 (Use vírgulas)', max_length=100)),
                ('elementos', models.TextField(blank=True, default='{}', verbose_name='Odontograma JSON')),
                ('tipo_servico', models.CharField(max_length=100, verbose_name='Tipo de Serviço')),
                ('cor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cor (Ex: A2)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações / Detalhes')),
                ('status', models.CharField(choices=[('PENDENTE_GESTOR', 'Aguardando Gestor'), ('RETRABALHO_DENTISTA', 'Retrabalho Dentista'), ('PENDENTE_OPERADOR', 'Aguardando Operador'), ('INICIADO', 'Em Produção'), ('FINALIZADO', 'Finalizado'), ('RETRABALHO_OPERADOR', 'Retrabalho Operador'), ('APROVADO', 'Aprovado')], default='PENDENTE_GESTOR', max_length=30)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('prazo_original', models.DateTimeField(blank=True, null=True)),
                ('prazo_ajustado', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_alocados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Historico_Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, max_length=30, null=True)),
                ('status_novo', models.CharField(max_length=30)),
                ('motivo_retrabalho', models.TextField(blank=True, null=True)),
                ('data_transicao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='pedidos.pedido')),
            ],
            options={
                'ordering': ['-data_transicao'],
            },
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='arquivos_protese/%Y/%m/')),
                ('descricao', models.CharField(blank=True, default='Arquivo STL', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='pedidos.pedido')),
            ],
        ),
    ]
