# Generated by Django 6.0 on 2026-01-21 03:19

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(error_messages={'unique': 'Já existe um usuário com este nome.'}, help_text='Necessário. 150 caracteres ou menos. Letras, dígitos e @/./+/-/_/espaços.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='O nome de usuário pode conter letras, números, espaços, hífens e underlines.', regex='^[\\w\\s.-]+$')], verbose_name='Nome de Usuário')),
                ('tipo_usuario', models.CharField(choices=[('GESTOR', 'Gestor'), ('CADISTA', 'Cadista'), ('DENTISTA', 'Dentista')], default='DENTISTA', max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número do CRO')),
                ('esta_arquivado', models.BooleanField(default=False, verbose_name='Está na Lixeira')),
                ('cadastro_confirmado', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_paciente', models.CharField(max_length=100)),
                ('tipo_servico', models.CharField(help_text='Ex: Coroa, Faceta, Protocolo', max_length=100)),
                ('dentes', models.CharField(help_text='Ex: 11, 12, 21 (Use vírgulas)', max_length=100)),
                ('cor', models.CharField(blank=True, help_text='Ex: A2, BL3', max_length=50, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente - Aguardando Análise'), ('EM_PRODUCAO', 'Em Produção'), ('CONCLUIDO', 'Concluído - Pronto para Entrega'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_entrega_prevista', models.DateField(blank=True, null=True)),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='arquivos_protese/%Y/%m/')),
                ('descricao', models.CharField(blank=True, default='Arquivo STL', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='pedidos.pedido')),
            ],
        ),
    ]
