# Generated by Django 6.0 on 2026-01-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cro',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número do CRO'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('GESTOR', 'Gestor'), ('CADISTA', 'Cadista'), ('DENTISTA', 'Dentista')], default='DENTISTA', max_length=20),
        ),
    ]
