# Generated by Django 6.0 on 2026-07-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='componentes_implante',
            field=models.TextField(blank=True, null=True, verbose_name='Componentes do Implante (JSON)'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('INICIADO', 'Iniciado'), ('RETRABALHO_OPERADOR', 'Retrabalho Operador'), ('RETRABALHO_CLIENTE', 'Retrabalho Cliente'), ('EM_APROVACAO', 'Em Aprovação'), ('FINALIZADO', 'Finalizado')], default='PENDENTE', max_length=30),
        ),
    ]
