# Generated by Django 6.0 on 2026-01-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='elementos',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dentes Selecionados'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações / Detalhes'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cor (Ex: A2)'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nome_paciente',
            field=models.CharField(max_length=100, verbose_name='Nome do Paciente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_servico',
            field=models.CharField(max_length=100, verbose_name='Tipo de Serviço'),
        ),
    ]
