# Generated by Django 6.0 on 2026-01-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_usuario_cro_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='esta_arquivado',
            field=models.BooleanField(default=False, verbose_name='Está na Lixeira'),
        ),
    ]
