# Generated by Django 6.0 on 2026-07-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_componentes_implante_alter_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='urgente',
            field=models.BooleanField(default=False, verbose_name='Urgente'),
        ),
    ]
