# Generated by Django 6.0 on 2026-01-28 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_elementos_pedido_observacoes_pedido_sexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='elementos',
            field=models.TextField(blank=True, default='{}', verbose_name='Odontograma JSON'),
        ),
    ]
