# Generated by Django 6.0 on 2026-01-04 21:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_usuario_esta_arquivado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(error_messages={'unique': 'Já existe um usuário com este nome.'}, help_text='Necessário. 150 caracteres ou menos. Letras, dígitos e @/./+/-/_/espaços.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='O nome de usuário pode conter letras, números, espaços, hífens e underlines.', regex='^[\\w\\s.-]+$')], verbose_name='Nome de Usuário'),
        ),
    ]
