# Generated by Django 6.0 on 2026-02-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_pedido_elementos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_PRODUCAO', 'Iniciado'), ('CONCLUIDO', 'Finalizado'), ('APROVADO', 'Aprovado')], default='PENDENTE', max_length=20),
        ),
    ]
