# Generated by Django 6.0 on 2026-07-30 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_urgente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='componentes_implante',
        ),
    ]
