# Generated by Django 6.0 on 2026-02-09 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='arquivo_entregavel',
            field=models.FileField(blank=True, null=True, upload_to='entregas/'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cadista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_alocados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='motivo_retrabalho',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Aguardando Início'), ('EM_PRODUCAO', 'Em Produção'), ('CONCLUIDO', 'Finalizado'), ('RETRABALHO', 'Ajuste Solicitado'), ('APROVADO', 'Aprovado')], default='PENDENTE', max_length=20),
        ),
    ]
