# Generated by Django 6.0 on 2026-07-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_remove_pedido_componentes_implante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_expediente', models.TimeField(default='08:00:00', verbose_name='Início do Expediente')),
                ('fim_expediente', models.TimeField(default='18:00:00', verbose_name='Fim do Expediente')),
            ],
        ),
    ]
