# Generated by Django 6.0 on 2026-08-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_configuracao'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaExcecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True, verbose_name='Data da Exceção')),
                ('trabalha', models.BooleanField(default=False, verbose_name='Trabalha?')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
            ],
        ),
    ]
