# Generated by Django 6.0 on 2026-08-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_diaexcecao'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='prazo_urgencia',
            field=models.PositiveIntegerField(default=3, verbose_name='Prazo de Urgência (Horas Úteis)'),
        ),
    ]
