# Generated by Django 6.0 on 2026-08-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_configuracao_prazo_urgencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cor (Ex: A2)'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='dentes',
            field=models.TextField(help_text='Ex: 11, 12, 21 (Use vírgulas)', verbose_name='Dentes Selecionados'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_servico',
            field=models.TextField(verbose_name='Tipo de Serviço'),
        ),
    ]
