# Generated by Django 6.0 on 2026-08-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_alter_pedido_cor_alter_pedido_dentes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='componentes_implante',
            field=models.TextField(blank=True, null=True, verbose_name='Componentes de Implante JSON'),
        ),
    ]
