# Generated by Django 6.0 on 2026-08-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_pedido_componentes_implante'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico_pedidos',
            name='detalhes_alteracao',
            field=models.TextField(blank=True, null=True, verbose_name='Detalhes da Alteração'),
        ),
    ]
