# Generated by Django 6.0 on 2026-08-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_historico_pedidos_detalhes_alteracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('INICIADO', 'Iniciado'), ('RETRABALHO_OPERADOR', 'Retrabalho Operador'), ('RETRABALHO_CLIENTE', 'Retrabalho Cliente'), ('EM_APROVACAO', 'Em Aprovação'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=30),
        ),
    ]
