# Generated by Django 6.0 on 2026-08-11 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='requer_implante',
            field=models.BooleanField(default=False, verbose_name='Requer Componentes de Implante'),
        ),
    ]
